version: '3.1'

services:

  account-service:
    build: .
    image: "ifg-proshop-account"
    ports:
      - 5000:8080
    links:
      - postgres:db

  postgres:
    build: db/.
    image: "ifg-proshop-account-db"
    ports:
      - 5432:5432
